# -*- coding: utf-8 -*-
import sys
try: sys.stdout.reconfigure(encoding="utf-8")
except Exception: pass
import re, openpyxl
from openpyxl.styles import Font, Alignment, PatternFill, Border, Side

# ---------- parse SRT for exact timecodes ----------
SRT = r"D:\TLP\KỊCH BẢN\KBP-001.srt"
def sec(x):
    h,m,r = x.split(":"); s,ms = r.split(","); return int(h)*3600+int(m)*60+int(s)+int(ms)/1000
def hhmmss(v):
    v=round(v); return f"{v//3600:02d}:{(v%3600)//60:02d}:{v%60:02d}"
E={}
n=0
for b in re.split(r"\n\s*\n", open(SRT, encoding="utf-8-sig").read().strip()):
    L=[l for l in b.splitlines() if l.strip()]
    if len(L)<2: continue
    a,bb=L[1].split(" --> "); n+=1; E[n]=(sec(a),sec(bb))

# ---------- locked character + style (identical every scene; ILLUSTRATION ONLY) ----------
CHAR = ("the SAME recurring heroine, identical in every scene: a comic/watercolor-illustrated "
        "woman in her late 30s with a friendly oval face, brown hair pulled back in a low "
        "ponytail with soft side-parted bangs, small teal-green stud earrings, a thin necklace, "
        "a green-and-purple horizontally striped short-sleeve scoop-neck t-shirt, light-blue "
        "high-waisted jeans cuffed at the ankles, and green canvas lace-up sneakers with white "
        "soles, warm calm expression")
STYLE = ("clean comic line-art with soft watercolor coloring, warm natural palette, gentle "
         "cel-style shading, with occasional subtle colorful watercolor paint-splatter accents "
         "(purple, blue, pink, yellow); stylized 2D illustrated characters only — never "
         "photorealistic, no real-person photography; absolutely NO text, letters, words or "
         "numbers anywhere in the frame")
# Front-loaded medium + hard anti-photoreal guards (Veo3 tends to default to realism)
ANIM  = ("2D HAND-DRAWN CARTOON ANIMATION, flat cel-shaded comic illustration with clean ink "
         "outlines and soft watercolor coloring (animated drawing, in the style of an illustrated "
         "storybook / motion-comic)")
NOREAL = ("IMPORTANT STYLE LOCK: everything is a drawn animated cartoon — NOT live action, NOT "
          "photorealistic, NOT 3D CGI, NOT a real human being; the character and all supporting "
          "figures are flat hand-drawn illustrations with visible ink linework and watercolor "
          "shading. No real people, no photographic faces, no text or letters anywhere")

def img(scene, cam):
    return (f"{ANIM}. {scene} The heroine is {CHAR}, kept clearly the central focus, drawn in flat "
            f"cartoon illustration. Supporting figures and props are drawn in the exact same "
            f"hand-drawn cartoon style. {STYLE}. {cam}. {NOREAL}.")

# ---------- scenes: (firstEntry, lastEntry, FR, VI, image-scene, video, note) ----------
S = [
(1,2,
 "Il y a une femme que nous connaissons toutes. C'est cette amie qui, au dernier moment, annule le rendez-vous.",
 "Có một người phụ nữ mà tất cả chúng ta đều biết. Đó là người bạn luôn hủy hẹn vào phút chót.",
 "A cozy apartment entryway at dusk; she stands by the door half-dressed to go out, coat still on a hook, giving a soft apologetic half-smile while holding a glowing phone; a faint round wall-clock hints the late hour.",
 "She lowers the phone with a gentle apologetic wince, fingers brushing the unworn coat; warm lamp glow, slow push-in.",
 "Mở đầu – giới thiệu nhân vật & hủy hẹn phút chót"),
(3,6,
 "Pas ce soir, je suis épuisé. On remet ça. Et au bout d'un moment, on commence à se dire qu'elle ne veut peut-être plus nous voir.",
 "Không phải tối nay, mình kiệt sức rồi. Để hôm khác nhé. Và sau một thời gian, ta bắt đầu nghĩ có lẽ cô ấy không còn muốn gặp mình nữa.",
 "Split scene: on the left she reclines exhausted on a sofa typing a short message, eyes heavy; on the right two simply-drawn friends at a café table glance at their phones with puzzled, faintly hurt expressions, an empty third chair beside them.",
 "She taps 'reschedule' and sighs; across the gutter the two friends exchange a worried look at the empty chair; gentle parallax between halves.",
 "Mệt mỏi, hoãn hẹn → bạn bè dần hiểu lầm"),
(7,8,
 "Mais voilà ce qui est troublant. La plupart du temps, ce n'est pas vous qu'elle fuit.",
 "Nhưng đây là điều đáng suy ngẫm. Phần lớn thời gian, không phải bạn là người cô ấy né tránh.",
 "Intimate close portrait against a soft blurred warm interior; she looks thoughtfully just off-camera, one hand resting near her cheek, a contemplative honest expression.",
 "Her gaze drifts and settles, a small reassuring shake of the head as warm light gently rises on her face.",
 "Lật ngược định kiến – không phải né tránh bạn"),
(9,10,
 "Elle protège quelque chose de bien plus précieux. Son énergie.",
 "Cô ấy đang bảo vệ một thứ quý giá hơn nhiều. Đó là năng lượng của cô ấy.",
 "She sits cross-legged on a window bench, hands cupped protectively over her chest where a soft warm orb of golden light glows; serene, guarded-yet-gentle posture; muted evening room behind.",
 "The chest orb pulses and brightens; she closes her eyes and curls slightly around it, breathing it in.",
 "Ẩn dụ năng lượng cần được bảo vệ"),
(11,12,
 "Parce que si vous êtes l'une de ces femmes qui, au fond, préfèrent sincèrement un vendredi soir en pyjama,",
 "Bởi vì nếu bạn là một trong những người phụ nữ mà, sâu thẳm bên trong, thật lòng thích một tối thứ Sáu trong bộ đồ ngủ,",
 "A snug living room on a Friday night; she lounges happily in soft cotton pajamas under a chunky knit blanket, woolly socks, a mug on the side table, fairy lights softly glowing along the shelf.",
 "She pulls the blanket cozier and wiggles her socked toes with a contented little smile; fairy lights twinkle slowly.",
 "Tối thứ Sáu đồ ngủ (nối cảnh, đối lập)"),
(13,14,
 "plutôt qu'une sortie en ville. Alors cette vidéo va sans doute vous décrire bien mieux que vous ne l'imaginez.",
 "hơn là một buổi đi chơi phố. Thì video này có lẽ sẽ mô tả bạn chính xác hơn bạn tưởng.",
 "Through a rain-speckled window she calmly watches a faded, blurred neon city nightlife outside (tiny umbrella silhouettes, smeared lights); she turns from the glass toward the viewer with a warm knowing look.",
 "Blurred neon outside drifts further out of focus as she turns from the window to meet the viewer's eyes with a soft 'I see you' smile.",
 "Đối lập đi chơi phố → nói thẳng với người xem"),
(15,16,
 "Aujourd'hui, nous allons comprendre la psychologie des femmes qui préfèrent rester chez elles.",
 "Hôm nay, chúng ta sẽ tìm hiểu tâm lý của những người phụ nữ thích ở nhà.",
 "She sits beside a softly glowing translucent silhouette of a human head filled with gentle drifting light-motes, gesturing toward it with an open inviting hand; calm study nook with a few plants.",
 "She gestures toward the glowing head-silhouette; the light-motes inside slowly swirl and settle.",
 "Mở chủ đề: tâm lý phụ nữ thích ở nhà"),
(17,17,
 "Celle que la société se permet d'appeler ennuyeuse ou renfermée.",
 "Người mà xã hội cho phép mình gọi là nhàm chán hay khép kín.",
 "She stands composed and dignified in a cool-toned plaza while faint translucent crowd silhouettes around her lean in and murmur, pointing; cool grey wash on the crowd, a warm glow held only on her.",
 "The grey crowd-shapes whisper and gesture around her; she stays still and unbothered, chin level, warm glow steady.",
 "Định kiến: bị gọi là nhàm chán/khép kín"),
(18,20,
 "Mais que la psychologie, elle, comprend d'une toute autre manière. D'abord, il faut saisir une chose très simple.",
 "Nhưng tâm lý học lại hiểu cô ấy theo một cách hoàn toàn khác. Trước tiên, cần nắm một điều rất đơn giản.",
 "Warm, empathetic medium shot in golden afternoon light; she sits relaxed in an armchair and raises one index finger in a gentle 'first, a simple point' teaching gesture, kind eyes.",
 "Soft golden light warms across her; her shoulders ease and she lifts one finger with a friendly explanatory tilt of the head.",
 "Tâm lý học hiểu khác – điều đơn giản đầu tiên"),
(21,22,
 "Toutes les femmes ne rechargent pas leur énergie de la même façon. Les extravertis se rechargent au contact des autres.",
 "Không phải người phụ nữ nào cũng nạp lại năng lượng theo cùng một cách. Người hướng ngoại nạp lại khi tiếp xúc với người khác.",
 "She stands at the side observing while, beside her, a simply-drawn cheerful extroverted woman in a bright dress laughs among three lively friends, glowing warm with energy; two soft battery-like light icons at different charge float nearby (no numbers).",
 "The extroverted woman lights up among her friends, her glow swelling; the heroine watches with a gentle understanding smile.",
 "Nạp năng lượng khác nhau – người hướng ngoại"),
(23,23,
 "Les conversations, le bruit, le mouvement, l'ambiance d'un groupe.",
 "Những cuộc trò chuyện, tiếng ồn, sự chuyển động, không khí của một nhóm.",
 "A lively house-party tableau in watercolor: several simply-drawn guests chatting, clinking cups, gesturing animatedly, warm buzzing atmosphere with swirling motion lines; the heroine stands quietly at the warm edge of the room.",
 "The guests animate with talk and movement, cups raised, energy rippling outward; the heroine observes calmly at the edge.",
 "Không khí náo nhiệt của một nhóm"),
(24,26,
 "Tout cela les allume de l'intérieur. Mais pour beaucoup d'autres femmes, c'est exactement l'inverse qui se produit.",
 "Tất cả thắp sáng họ từ bên trong. Nhưng với nhiều phụ nữ khác, điều ngược lại hoàn toàn xảy ra.",
 "Diptych: left, the extroverted woman radiant with a bright inner glow amid the party; right, the heroine quietly stepping back through a doorway, her own glow visibly dimming, a tired but calm expression.",
 "Left half the extrovert flares brighter; right half the heroine steps back and her glow softly fades as the party blurs behind her.",
 "Người hướng ngoại bừng sáng vs người kia ngược lại"),
(27,28,
 "Chaque interaction sociale, même la plus agréable, vient grignoter doucement leur énergie,",
 "Mỗi tương tác xã hội, kể cả dễ chịu nhất, đều âm thầm bào mòn năng lượng của họ,",
 "She shares a pleasant smile with a kind simply-drawn neighbour over a fence, yet a thin translucent ribbon of light is gently drawn out of her chest; her smile is warm but edged with fatigue; sunny but soft setting.",
 "She nods politely as a faint glowing ribbon is gently tugged from her chest; her smile softens with quiet weariness.",
 "Tương tác dễ chịu vẫn bào mòn năng lượng"),
(29,29,
 "comme une batterie qui se vide, lentement, heure après heure.",
 "như một viên pin cạn dần, từ từ, giờ này qua giờ khác.",
 "Close on her hands cradling a soft glowing orb shaped like a battery whose warm light is draining downward to near-empty; faint clock-hand shadows sweep across the wall behind to suggest passing hours (no numbers).",
 "The orb's glow slowly drains from full to low while soft clock-shadows sweep behind; her expression grows quietly tired.",
 "Ẩn dụ pin cạn dần theo thời gian"),
(30,32,
 "Et alors, elles ont besoin de quelque chose de très précis : du silence, du calme, de l'espace mental,",
 "Và rồi, họ cần một điều gì đó rất cụ thể: sự im lặng, sự bình yên, không gian trong tâm trí,",
 "She stands in a wide, airy, almost empty minimalist room with pale light and enormous negative space, eyes closed, breathing deeply; faint chaotic noise-shapes dissolve away from around her head into the calm.",
 "She inhales slowly; the lingering noise-shapes melt away and the empty space seems to widen and quiet around her.",
 "Cần: im lặng, bình yên, không gian tâm trí"),
(33,34,
 "et il existe en général un seul endroit où tout cela devient possible. La maison.",
 "và thường chỉ có một nơi duy nhất khiến tất cả điều đó trở nên khả thi. Đó là ngôi nhà.",
 "Exterior dusk: she walks a calm path toward a small house whose windows glow warm and inviting, everything else around muted blue-grey; then framed in the doorway bathed in golden interior light.",
 "She walks toward the glowing house; the warm window-light grows as she nears and steps into the doorway glow, shoulders relaxing.",
 "Nơi duy nhất khả thi: ngôi nhà"),
(35,36,
 "Voilà pourquoi, pour tant de femmes, rester chez soi n'a rien à voir avec l'ennui.",
 "Đó là lý do, với rất nhiều phụ nữ, ở nhà chẳng liên quan gì đến sự chán nản.",
 "Inside her warm home she is genuinely engaged and content — watering a windowsill plant, a book open on the couch, soft music implied by floating note-shapes — clearly absorbed, not bored.",
 "She tends the plant and glances at her open book with a contented purposeful air; warm steady light, note-shapes drifting.",
 "Ở nhà không hề là chán nản"),
(37,37,
 "C'est littéralement revenir se brancher sur le chargeur.",
 "Đó thực sự là quay về cắm sạc lại chính mình.",
 "She settles into a favourite armchair as a soft warm glow visibly flows back into her chest like recharging; a gentle aura of restored energy ripples around her; cozy reading lamp.",
 "The warm glow streams back into her body; her face brightens and softens as if her battery is refilling.",
 "Về nhà = cắm sạc lại bản thân"),
(38,38,
 "En psychologie, on parle de la théorie du niveau optimal de stimulation.",
 "Trong tâm lý học, người ta gọi đó là lý thuyết mức kích thích tối ưu.",
 "At a tidy desk she studies a soft glowing arc/curve of light hovering above an open notebook (a pure shape, no text or numbers); a mug of tea steams beside warm desk light; an intrigued, scholarly-but-warm mood.",
 "She traces the glowing curve in the air with a fingertip and it gently re-draws itself; steam curls from the mug.",
 "Khái niệm: mức kích thích tối ưu"),
(39,40,
 "Et elle dit quelque chose de fascinant. Chaque personne possède un seuil différent de stimulation pour se sentir bien.",
 "Và nó nói lên một điều thú vị. Mỗi người có một ngưỡng kích thích khác nhau để cảm thấy thoải mái.",
 "She gestures between two simply-drawn women — one beside a small soft glow, one beside a large bright glow — illustrating different personal thresholds; she leans in with intrigued delight; clean warm backdrop.",
 "She points from the small glow to the large glow, eyebrows lifting with fascination as each glow gently pulses.",
 "Mỗi người có ngưỡng kích thích khác nhau"),
(41,42,
 "Certaines ont besoin de beaucoup d'agitation pour se sentir vivante, d'autres en ont besoin de très peu.",
 "Một số người cần rất nhiều sự náo nhiệt để thấy mình đang sống, người khác chỉ cần rất ít.",
 "Diptych: left, a simply-drawn woman spins joyfully amid swirling colourful busy motion (confetti-like shapes); right, the heroine sits serenely with a single candle and a cup, content with very little; clear tonal contrast.",
 "Left, the dancer whirls amid swirling colour; right, the heroine sits perfectly still and content as her single candle flickers.",
 "Đối lập: cần nhiều vs cần rất ít kích thích"),
(43,45,
 "Et lorsque ce seuil est dépassé, apparaissent la fatigue mentale, la saturation, cette envie soudaine de disparaître quelques heures.",
 "Và khi ngưỡng đó bị vượt qua, sự mệt mỏi tinh thần xuất hiện, sự quá tải, cái khao khát đột ngột được biến mất vài giờ.",
 "In an over-bright crowded space she presses both hands to her temples, overwhelmed, surrounded by a muted swirl of overlapping noise-lines and shapes; her eyes flick longingly toward a calm exit doorway.",
 "The chaotic shapes swirl tighter around her head; she winces, then glances toward the quiet doorway, aching to slip away.",
 "Vượt ngưỡng: quá tải, muốn biến mất"),
(46,48,
 "Alors non. Préférer rester chez soi, ce n'est pas de la paresse. Ce n'est pas être asocial.",
 "Vậy nên không. Thích ở nhà không phải là lười biếng. Cũng không phải là người xa lánh xã hội.",
 "She stands upright and self-assured, calmly waving away two faint floating label-clouds (a drooping 'lazy' wilt-shape and a cold turned-back 'antisocial' shape) that dissolve into light; her expression is kind and clear.",
 "She gives a small firm head-shake and a gentle hand-wave; the faint label-shapes dissolve as her look turns warm and certain.",
 "Không phải lười, không phải xa lánh"),
(49,50,
 "C'est simplement la façon dont votre système nerveux est réglé. Mais il y a encore quelque chose de plus profond.",
 "Đó đơn giản là cách hệ thần kinh của bạn được thiết lập. Nhưng còn có điều gì đó sâu sắc hơn nữa.",
 "Semi-transparent view: a gentle glowing branching nerve-pattern flows calmly through her serene silhouette like fine tree-roots of light; she then leans slightly closer to the viewer as the light dims for an intimate tone.",
 "Soft pulses travel along the glowing nerve-branches through her calm silhouette; she leans in as the light gently lowers.",
 "Do hệ thần kinh – và còn sâu hơn nữa"),
(51,53,
 "Pour beaucoup de femmes, rester à la maison est aussi une question de contrôle. Parce que dehors, le monde est imprévisible.",
 "Với nhiều phụ nữ, ở nhà còn là vấn đề kiểm soát. Bởi vì bên ngoài, thế giới khó lường.",
 "Split: left, she calmly and deliberately arranges her own cozy shelf, each object placed just so, quietly empowered; right, the same woman stands tense at the edge of a chaotic blurred street with rushing umbrellas and smeared traffic.",
 "Left she sets a last object precisely with a satisfied breath; right she hesitates at the curb as blurred traffic rushes past, clutching her bag.",
 "Kiểm soát ở nhà vs thế giới ngoài khó lường"),
(54,55,
 "Le bruit, les inconnus, les plans qui changent, les conversations superficielles.",
 "Tiếng ồn, người lạ, những kế hoạch thay đổi liên tục, những cuộc trò chuyện hời hợt.",
 "She stands amid swirling simple symbols of chaos: jagged noise-bursts, faceless grey stranger-silhouettes, shifting tangled arrow-shapes, and tiny hollow speech-bubble outlines (empty, no text), all pressing gently inward; she stays guarded.",
 "The noise-bursts, grey strangers, shifting arrows and empty speech-bubbles swirl and crowd around her; she holds herself still and wary.",
 "Ồn ào, người lạ, kế hoạch đổi, nói hời hợt"),
(56,57,
 "Ce fameux : et vous, vous faites quoi dans la vie ? Légèrement gênant, mais à la maison, tout change.",
 "Cái câu quen thuộc: còn bạn, bạn làm nghề gì? Hơi gượng gạo, nhưng ở nhà, mọi thứ thay đổi.",
 "Left, at a stiff networking gathering a simply-drawn stranger leans in with a probing question and she gives a polite but visibly awkward smile, leaning back; right, that scene dissolves as she steps home and reaches for a warm lamp dial.",
 "The stranger leans in and she offers a stiff polite smile; the awkward scene dissolves as she turns the lamp dial and warm light blooms.",
 "Câu hỏi xã giao gượng gạo → về nhà mọi thứ đổi"),
(58,59,
 "C'est vous qui choisissez la lumière, le son, la température, la musique, et même le rythme du temps qui passe.",
 "Chính bạn chọn ánh sáng, âm thanh, nhiệt độ, âm nhạc, và cả nhịp trôi của thời gian.",
 "Inside her cozy home she is surrounded by soft icons she controls: a warm dimmable lamp, gentle sound-wave ripples, a glowing cozy thermostat orb, floating music-notes, and a softly slow-ticking wall clock — all in harmony around her.",
 "She gestures and each soft icon responds — lamp warms, sound-waves ripple, notes drift, the clock slows — in calm harmony.",
 "Tự chọn ánh sáng, âm thanh, nhiệt độ, nhạc, nhịp thời gian"),
(60,62,
 "Pour une femme sensible, ou qui vit avec de l'anxiété, ce contrôle n'est pas un luxe. C'est une paix intérieure.",
 "Với một người phụ nữ nhạy cảm, hay đang sống chung với lo âu, sự kiểm soát ấy không phải xa xỉ. Đó là sự bình yên nội tâm.",
 "A tender close shot: she sits wrapped in a soft shawl with one hand over her heart and eyes closed, a gentle healing aura of pale light expanding around her in a safe, dim, candle-lit corner.",
 "She breathes slowly with a hand on her heart; the pale healing aura softly expands and her face fully calms.",
 "Người nhạy cảm/lo âu – đây là bình yên nội tâm"),
(63,64,
 "C'est souvent le seul endroit où son cerveau peut enfin se détendre, pour de vrai, sans être sur ses gardes.",
 "Đó thường là nơi duy nhất khiến bộ não cô ấy cuối cùng thực sự được thư giãn, mà không phải đề phòng.",
 "She melts deep into a soft sofa, head tipped back, arms loose, shoulders fully dropped; a faint soothing glow loosens around her head as the day's tension unwinds; warm lamp, blanket pooled nearby.",
 "Her body sinks into the cushions, head tipping back, guarded tension visibly releasing as the soft glow around her head softens.",
 "Nơi duy nhất não bộ thật sự thả lỏng"),
(65,66,
 "Et voici ce que beaucoup ignorent. Les études montrent que les personnes qui savent apprécier la solitude",
 "Và đây là điều nhiều người không biết. Các nghiên cứu cho thấy những người biết tận hưởng sự cô độc",
 "She turns to the viewer with a subtle 'here's a secret' look, then is shown peacefully alone at a sunlit window seat savouring her own company, a calm contented half-smile, a plant and open journal beside her.",
 "She gives a knowing glance to camera, then settles at the window seat with a slow contented smile, at ease in her solitude.",
 "Dẫn dắt – người biết tận hưởng cô độc (nối cảnh)"),
(67,68,
 "présentent souvent des niveaux plus élevés de créativité, d'introspection, et de capacité à résoudre des problèmes.",
 "thường có mức sáng tạo cao hơn, khả năng tự soi xét nội tâm, và khả năng giải quyết vấn đề.",
 "She sketches and writes in a notebook as soft glowing imaginative blossoms and tiny puzzle-pieces of light rise from the page and gently click together above her hands; cozy creative desk, warm focused light.",
 "Her hand sketches; colourful shapes bloom upward and floating puzzle-pieces drift together and softly lock into place.",
 "Sáng tạo, nội tâm, giải quyết vấn đề cao hơn"),
(69,70,
 "Parce que lorsque le bruit constant disparaît, l'esprit recommence enfin à penser.",
 "Bởi vì khi tiếng ồn liên tục biến mất, tâm trí cuối cùng bắt đầu suy nghĩ trở lại.",
 "Chaotic noise-lines around her thin out and dissolve to reveal a clear calm space; a single bright, clean point of thought-light blooms above her head; soft neutral background, a relieved focused expression.",
 "The tangled noise-lines fade outward; a clear glowing point of thought blooms above her head as quiet clarity returns.",
 "Hết ồn ào – tâm trí suy nghĩ trở lại"),
(71,72,
 "Les meilleures idées ne naissent presque jamais au milieu d'une fête bondée. Elles arrivent dans le silence, sur le canapé,",
 "Những ý tưởng hay nhất gần như chẳng bao giờ nảy sinh giữa một bữa tiệc đông đúc. Chúng đến trong im lặng, trên ghế sofa,",
 "Diptych: left, in a crowded blurred party she stands with a dim, empty idea-bulb shape above her (no spark); right, alone on a quiet sofa at night a warm bright idea-light suddenly blooms above her, eyes lighting up.",
 "Left her idea-bulb flickers weakly in the crowd; right, on the silent sofa a warm idea-light suddenly blooms and her eyes widen with delight.",
 "Ý tưởng không đến ở tiệc đông – mà trên sofa yên tĩnh"),
(73,75,
 "pendant une promenade, ou à deux heures du matin, quand soudain votre esprit relie entre elles des choses que personne d'autre n'avait vu.",
 "trong một buổi đi dạo, hay lúc hai giờ sáng, khi bất chợt tâm trí bạn kết nối những điều mà chẳng ai khác từng nhận ra.",
 "Night-time: she walks a quiet lamp-lit street, then is shown awake by a window at 2 a.m.; above her, scattered glowing dots draw connecting lines into a small constellation of linked ideas, her face lit with discovery.",
 "As she walks then pauses at the night window, glowing dots above her draw connecting lines into a constellation; her face lights with insight.",
 "Đi dạo / 2 giờ sáng – kết nối ý tưởng mới"),
(76,79,
 "Rester chez soi, ce n'est pas ne rien faire. C'est très souvent là que se passe le plus important. Penser.",
 "Ở nhà không có nghĩa là chẳng làm gì cả. Rất thường, đó lại là nơi điều quan trọng nhất diễn ra. Suy nghĩ.",
 "She sits by a rain-streaked window, chin resting on her hand, deep in thought; a rich, gently swirling glow of contemplation surrounds her head; a cooling cup of tea and a closed book nearby — quietly, importantly busy inside.",
 "She rests her chin on her hand, gaze going distant and inward as the swirling contemplation-glow slowly turns around her.",
 "Ở nhà không phải vô ích – đó là lúc suy nghĩ"),
(80,81,
 "Pourtant, il y a quelque chose de curieux. La société semble obsédée par l'inverse.",
 "Thế nhưng, có một điều kỳ lạ. Xã hội dường như bị ám ảnh bởi điều ngược lại.",
 "She stands small in the foreground, tilting her head with a curious puzzled look, while behind her loom faint oversized blurred billboards and glowing screens all radiating restless 'go out' energy.",
 "She tilts her head, one eyebrow raised, as the towering blurred screens behind her flicker and loom with restless energy.",
 "Điều kỳ lạ – xã hội ám ảnh điều ngược lại"),
(82,82,
 "Sortir, voyager, faire la fête, multiplier les expériences.",
 "Ra ngoài, đi du lịch, tiệc tùng, trải nghiệm thật nhiều.",
 "A swirling montage ring around her of simple watercolor icons: a nightclub doorway, a little airplane, clinking party cups, a camera, a suitcase, cocktail glasses — all flashy and spinning — while she stands calm and slightly detached at the centre.",
 "The ring of go-out icons spins faster around her, bright and dizzying; she stays calm and still at the quiet centre.",
 "Ra ngoài, du lịch, tiệc, trải nghiệm dồn dập"),
(83,84,
 "Des réseaux sociaux remplis de gens qui vivent leur meilleure vie, comme si être constamment dehors était synonyme de bonheur.",
 "Mạng xã hội đầy những người sống cuộc đời tuyệt nhất của họ, như thể cứ ra ngoài liên tục là đồng nghĩa với hạnh phúc.",
 "She holds a phone showing a softly glowing endless feed of glamorous simply-drawn smiling figures at beaches and parties (faces only, no readable text); her own expression is faintly skeptical and wistful in a dim room.",
 "She scrolls the glowing feed of perfect-looking lives, then lowers the phone with a doubtful raised eyebrow and a small sigh.",
 "Mạng xã hội hào nhoáng – ngỡ ra ngoài là hạnh phúc"),
(85,86,
 "Mais si votre meilleure vie ne ressemblait pas du tout à ça. Et si votre soirée parfaite était quelque chose de beaucoup plus simple.",
 "Nhưng nếu cuộc đời tuyệt nhất của bạn chẳng hề giống như thế thì sao. Và nếu buổi tối hoàn hảo của bạn là điều gì đó đơn giản hơn nhiều thì sao.",
 "She turns away from the bright noisy phone-glow toward her warm, simple cozy living room behind her, a thoughtful questioning expression; the glossy feed fades to soft focus over her shoulder.",
 "She lowers the phone and turns toward the warm room; the glossy feed blurs away behind her as her gaze softens with curiosity.",
 "Nếu cuộc đời tuyệt nhất lại đơn giản hơn nhiều?"),
(87,87,
 "Une série, un plaid, un plat chaud, une bougie et zéro obligation.",
 "Một bộ phim, một chiếc chăn mềm, một món ăn nóng, một ngọn nến và không một nghĩa vụ nào.",
 "Cozy still-life around her: a softly glowing screen flickering a show, a warm plaid blanket over her shoulders, a steaming bowl of food in her lap, a single lit candle — she is snug, free and at peace on the couch.",
 "Steam curls from the bowl, the candle flame sways, the screen glows softly as she pulls the plaid closer with a content sigh.",
 "Phim – chăn – món nóng – nến – không nghĩa vụ"),
(88,89,
 "Pour certaines femmes, cela n'est pas de la tristesse. C'est la paix.",
 "Với một số phụ nữ, đó không phải là nỗi buồn. Đó là sự bình yên.",
 "She stretches out fully relaxed and serene across the sofa in soft warm light, no hint of sadness — a calm, deeply peaceful expression; gentle dusk light through sheer curtains.",
 "She stretches luxuriously and settles, her face easing from neutral into a calm, genuinely peaceful smile.",
 "Đó không phải buồn – mà là bình yên"),
(90,91,
 "Et le reconnaître, c'est déjà une forme de connaissance de soi. Cela dit, il faut être honnête sur un point important.",
 "Và nhận ra điều đó đã là một dạng thấu hiểu bản thân. Dù vậy, cần thành thật về một điểm quan trọng.",
 "A serene portrait with a soft mirrored reflection of herself beside her (gentle self-awareness motif); then she turns to the viewer with a sincere, slightly more serious open-handed gesture as the mood steadies.",
 "Her mirrored reflection softly pulses with a knowing smile; she then turns to the viewer with an honest, more serious open gesture.",
 "Thấu hiểu bản thân – nhưng cần thành thật một điều"),
(92,94,
 "Toutes les femmes ne restent pas chez elles pour les mêmes raisons. Pour certaines, rester à la maison peut cacher quelque chose de plus sombre.",
 "Không phải phụ nữ nào ở nhà cũng vì cùng một lý do. Với một số người, ở nhà có thể che giấu điều gì đó u tối hơn.",
 "Two contrasting versions of a woman at home side by side: one in bright warm light, serene; the other in dim cool light, withdrawn with a subtle shadow creeping across the wall; the heroine stands between them, gesturing thoughtfully.",
 "She gestures from the bright peaceful figure to the dim withdrawn one as a soft shadow slowly lengthens across the second's wall.",
 "Cùng ở nhà nhưng lý do khác – có mặt u tối hơn"),
(95,97,
 "De l'anxiété sociale, des expériences blessantes avec les autres, ou parfois même une dépression qui s'installe en silence.",
 "Sự lo âu xã hội, những trải nghiệm tổn thương từ người khác, hoặc đôi khi là cả một nỗi trầm cảm âm thầm len lỏi.",
 "In dim, desaturated light she sits hunched on the edge of a bed; faint blurred turned-away figures hover as painful memories behind her, and a soft heavy grey haze settles quietly around her shoulders; a hollow, distant gaze.",
 "Her hand hovers anxiously near her chest as blurred figures fade behind her and a slow grey haze settles around her motionless shoulders.",
 "Lo âu xã hội, tổn thương, trầm cảm âm thầm"),
(98,99,
 "Dans ces cas-là, la maison devient une chose étrange. À la fois un refuge et une cage.",
 "Trong những trường hợp đó, ngôi nhà trở thành một điều kỳ lạ. Vừa là nơi trú ẩn, vừa là một chiếc lồng.",
 "She sits sheltered in a warm pool of lamplight, yet soft elongated shadow-bars (from a window frame) fall gently across the room like cage bars — half comforting refuge, half quiet cage; ambivalent expression.",
 "Warm shelter-light glows around her while faint bar-shaped shadows slide across the floor; her gaze flickers between safe and trapped.",
 "Ngôi nhà kỳ lạ – vừa trú ẩn vừa là lồng"),
(100,101,
 "C'est pourquoi il existe une question essentielle pour distinguer les deux. Est-ce que vous restez chez vous parce que cela vous fait du bien ?",
 "Vì thế có một câu hỏi cốt yếu để phân biệt hai điều đó. Bạn ở nhà vì điều đó khiến bạn thấy tốt hơn?",
 "She faces the viewer with one open hand raised as if posing a gentle but crucial question; behind her a faint glowing balance/scale-of-light motif hovers; soft focused key-light on her thoughtful face.",
 "She raises an open hand toward the viewer, the faint balance-of-light tilting softly behind her as she poses the question.",
 "Câu hỏi cốt yếu: ở nhà vì thấy tốt hơn?"),
(102,103,
 "Ou parce que sortir vous semble tout simplement trop lourd à porter ? La première, c'est de la tranquillité.",
 "Hay vì việc ra ngoài đơn giản là quá nặng nề để gánh vác? Cái đầu tiên là sự an yên.",
 "Left, a heavier version of her hesitates at the front door, shoulders bowed as if carrying an invisible weight, unable to step out; right, a bright serene version sits calmly bathed in warm light, fully at peace — clear contrast.",
 "Left she stalls at the door under an invisible load; right the serene version breathes easy with a soft genuine smile in warm light.",
 "Hay vì ra ngoài quá nặng nề? – Vế 1: an yên"),
(104,105,
 "La seconde, c'est de l'évitement. Et comprendre cette différence change absolument tout.",
 "Cái thứ hai là sự né tránh. Và hiểu được sự khác biệt ấy thay đổi hoàn toàn mọi thứ.",
 "She turns her face and body away from the door and the outside world in a closed-off, avoidant posture under cool muted light; then a wash of warm clarifying light begins to sweep across her into an understanding expression.",
 "She turns away protectively in cool light, then warm clarifying light sweeps across her face into calm understanding.",
 "Vế 2: né tránh – và hiểu khác biệt thay đổi tất cả"),
(106,108,
 "Mais pour les femmes qui aiment sincèrement être chez elles, il n'y a aucun sentiment de manquer quoi que ce soit. Elles vivent simplement autrement.",
 "Nhưng với những phụ nữ thật lòng yêu thích ở nhà, không hề có cảm giác bỏ lỡ bất cứ điều gì. Họ chỉ đơn giản sống theo cách khác.",
 "She relaxes radiantly happy in her warm home while, through the window, a faint distant party-glow holds absolutely no pull on her; she simply turns back to her cozy comfort, fully content (no FOMO).",
 "She glances once at the faint window party-glow, smiles, and turns calmly back to her cozy comfort, utterly unbothered.",
 "Yêu thích ở nhà – không bỏ lỡ gì, chỉ sống khác đi"),
(109,110,
 "Elles trouvent du bonheur dans de petits rituels. Le café du matin, encore tiède entre les mains.",
 "Họ tìm thấy hạnh phúc trong những nghi thức nhỏ bé. Tách cà phê buổi sáng, vẫn còn ấm trong lòng bàn tay.",
 "Soft morning light in a quiet kitchen nook; close on her cradling a warm mug of coffee in both hands near her face, eyes gently closed, faint rising steam, a small blissful smile; a window with soft daylight behind.",
 "She wraps both hands around the warm mug, lifts it close and inhales the rising steam with eyes closed and a small blissful smile.",
 "Hạnh phúc trong nghi thức nhỏ – cà phê sáng ấm tay"),
(111,112,
 "Ce coin précis du canapé qui est devenu le leur. La façon dont la lumière entre par la fenêtre, en fin d'après-midi,",
 "Cái góc quen thuộc trên ghế sofa đã trở thành của riêng họ. Cách ánh sáng len qua khung cửa sổ, vào cuối buổi chiều,",
 "She curls into her own well-loved corner of the sofa, cushions perfectly shaped to her, as warm late-afternoon light streams in through a nearby window casting a soft golden rectangle across her and the floor.",
 "She nestles perfectly into her sofa corner as the golden window-light slowly shifts across her and the cushions, dust motes drifting.",
 "Góc sofa của riêng cô – ánh chiều qua cửa sổ"),
(113,114,
 "de minuscules moments que la plupart des gens ne remarquent même pas, parce qu'ils courent déjà vers le plan suivant.",
 "những khoảnh khắc nhỏ xíu mà phần lớn mọi người thậm chí chẳng nhận ra, bởi họ đã vội lao về phía kế hoạch tiếp theo.",
 "She sits perfectly still savouring a tiny golden-hour moment while around her, blurred simply-drawn figures rush past in motion-streaks, checking watches and hurrying onward — she alone is calm and in sharp focus.",
 "She holds still, savouring the light, while blurred hurrying figures streak past around her; she remains serene and crisply in focus.",
 "Khoảnh khắc nhỏ bị bỏ quên – người khác vội vã"),
(115,115,
 "En psychologie, on appelle cela une préférence pour la basse stimulation.",
 "Trong tâm lý học, người ta gọi đó là sự ưa thích mức kích thích thấp.",
 "A calm, minimal composition: she rests in a serene low-stimulation room with only a few soft elements — a single plant, a folded blanket, gentle even light — balanced and completely at ease.",
 "She breathes slowly and evenly in the quiet minimal room, settling deeper into calm, a softly balanced expression.",
 "Khái niệm: ưa thích mức kích thích thấp"),
(116,117,
 "Des femmes qui n'ont pas besoin que le monde les divertisse en permanence. Parce que leur monde intérieur est déjà suffisamment riche.",
 "Những phụ nữ không cần thế giới phải giải trí cho họ liên tục. Bởi thế giới nội tâm của họ vốn đã đủ phong phú.",
 "She sits content and self-sufficient as faint flashy entertainment icons drift toward her and quietly fade, unneeded; meanwhile a rich, vibrant glow of imaginative shapes begins blooming gently around her head and shoulders.",
 "Flashy icons drift in and dissolve as she calmly ignores them; a lush imaginative glow slowly unfolds around her head instead.",
 "Không cần thế giới giải trí – nội tâm đã phong phú"),
(118,119,
 "Leur pensée, leurs idées, leur projet, leur imagination. Tout un univers qui ne demande qu'à être habité.",
 "Những suy nghĩ, những ý tưởng, những dự định, trí tưởng tượng của họ. Cả một vũ trụ chỉ chờ được bước vào sinh sống.",
 "Around her float distinct soft glowing motifs — a swirling thought, a bright idea-spark, a small blueprint-like plan, a dreamy imaginative swirl — which open out behind her into an entire gentle starry cosmos of little dream-worlds she gazes into.",
 "The glowing motifs orbit her one by one, then bloom outward into a vast soft cosmos she leans toward with wonder.",
 "Suy nghĩ–ý tưởng–dự định–tưởng tượng → cả vũ trụ nội tâm"),
(120,121,
 "Alors, si vous êtes une femme qui décline une invitation sans culpabilité, qui savoure réellement un samedi en solitaire,",
 "Vậy nên, nếu bạn là người phụ nữ từ chối một lời mời mà không hề thấy tội lỗi, người thật sự tận hưởng một ngày thứ Bảy một mình,",
 "Left, she serenely declines a held-out invitation card from a simply-drawn friend with a calm guilt-free smile; right, she blissfully enjoys a lazy solo Saturday at home in soft daylight, stretching happily.",
 "Left she gently raises a hand to decline the invite with an easy smile; right she stretches into her solo Saturday, beaming and relaxed.",
 "Từ chối không tội lỗi – tận hưởng thứ Bảy một mình"),
(122,123,
 "qui préfère revoir sa série préférée plutôt que de se forcer à sortir, sachez qu'il n'y a rien qui cloche chez vous.",
 "người thà xem lại bộ phim yêu thích còn hơn ép mình ra ngoài, hãy biết rằng bạn chẳng có gì sai trái cả.",
 "She happily rewatches a beloved show on a softly glowing screen, wrapped in a blanket, as a faint 'go out' prompt-shape fades away beside her; then she turns to the viewer with a warm, reassuring affirming look.",
 "She settles in to rewatch her show as the faint go-out prompt dissolves, then turns to camera with a warm reassuring nod.",
 "Thà xem lại phim – bạn chẳng có gì sai cả"),
(124,126,
 "Vous n'êtes pas cassée, vous n'êtes pas trop ceci ou pas assez cela. Vous êtes simplement conçue pour autre chose.",
 "Bạn không hề hỏng hóc, bạn không quá thế này hay thiếu thế kia. Bạn chỉ đơn giản được tạo ra cho một điều khác.",
 "She stands whole and self-assured as faint critical label-shapes around her dissolve into light; then she is shown standing serenely apart, gently glowing, clearly made for a different, deeper kind of life.",
 "The faint label-shapes dissolve around her; she stands taller, a soft glow rising, a quietly proud and peaceful expression.",
 "Bạn không hỏng hóc – chỉ được tạo ra cho điều khác"),
(127,128,
 "La profondeur plutôt que le bruit, la paix plutôt que le spectacle, la présence plutôt que l'agitation.",
 "Chiều sâu thay vì tiếng ồn, sự bình yên thay vì phô diễn, sự hiện diện trọn vẹn thay vì sự xáo động.",
 "Triptych of gentle contrasts around her: deep calm still water vs fading jagged noise; soft peaceful light vs a dimming flashy spotlight; grounded stillness vs blurring agitation — she stands centred, choosing the calm side each time.",
 "On each side the harsh element (noise, spotlight, agitation) fades while the calm element glows; she stays centred and serene.",
 "Chiều sâu/bình yên/hiện diện thay vì ồn ào/phô diễn/xáo động"),
(129,130,
 "Maintenant, je suis curieuse. Et vous, qu'est-ce que vous préférez vraiment au fond ?",
 "Giờ thì, tôi tò mò. Còn bạn, sâu thẳm bên trong, bạn thật sự thích điều gì?",
 "She leans gently toward the viewer with a genuinely curious, warm expression, head tilted, one hand lightly open in invitation; soft intimate light, simple cozy backdrop.",
 "She tilts her head toward the viewer, eyebrows lifting with sincere curiosity, an open inviting hand and a warm smile.",
 "Tôi tò mò – sâu thẳm bạn thật sự thích gì?"),
(131,132,
 "Rester chez vous ou sortir dès que l'occasion se présente ? Dites-moi la vérité dans les commentaires.",
 "Ở nhà hay ra ngoài ngay khi có cơ hội? Hãy nói tôi nghe sự thật trong phần bình luận.",
 "She stands at the centre between two clear choices: a cozy glowing home on one side, a bright lively going-out scene on the other; then she gestures warmly downward toward an implied comment space, inviting and encouraging (no text icons).",
 "She glances from the cozy-home side to the lively go-out side, then gestures invitingly downward with an encouraging nod.",
 "Ở nhà hay ra ngoài? – mời bình luận"),
(133,134,
 "Parce qu'il y a quelque chose de fascinant chez les femmes qui préfèrent rester chez elles.",
 "Bởi có điều gì đó thật cuốn hút ở những phụ nữ thích ở nhà.",
 "A captivating, almost luminous portrait of her at home, quietly magnetic and self-possessed, framed by a soft warm glow and a gently blurred cozy interior.",
 "A soft luminous glow gathers around her; she gives a quietly captivating, knowing half-smile to camera.",
 "Có điều gì đó thật cuốn hút ở những phụ nữ thích ở nhà"),
(135,136,
 "Et quand on comprend enfin la véritable raison psychologique derrière tout cela, beaucoup de choses se mettent soudain à avoir du sens.",
 "Và khi ta cuối cùng hiểu được lý do tâm lý thật sự đằng sau tất cả, rất nhiều điều bỗng nhiên trở nên có ý nghĩa.",
 "Soft glowing fragments of understanding drift together and lock into one clear luminous picture around her as a warm clarifying light blooms across her face; a dawning, relieved, satisfied realization.",
 "Glowing fragments drift in and click into a clear whole around her; warm light blooms over her face as understanding settles in.",
 "Hiểu lý do thật sự – mọi thứ bỗng có ý nghĩa"),
(137,139,
 "Dans la prochaine vidéo, nous allons parler de quelque chose qui vous décrira peut-être encore mieux. Je vous attends là-bas.",
 "Trong video tiếp theo, chúng ta sẽ nói về một điều có lẽ sẽ mô tả bạn còn chính xác hơn nữa. Tôi đợi bạn ở đó nhé.",
 "She gestures forward toward a soft glowing doorway of light suggesting the next video, an inviting forward-looking expression; then a gentle friendly farewell wave toward the viewer, a cozy warmly-lit home behind her.",
 "She gestures toward the glowing doorway with an anticipatory smile, then lifts her hand in a warm friendly farewell wave.",
 "Dẫn video sau – chào tạm biệt, hẹn gặp lại"),
]

# ---------- build workbook ----------
wb = openpyxl.Workbook(); ws = wb.active; ws.title = "Storyboard KBP-001"
headers = ["STT","Timecode (bắt đầu - kết thúc)","Thời lượng (giây)","Nội dung gốc (FR)",
           "Bản dịch tiếng Việt","Image Prompt (EN) - NO TEXT","Video Prompt (EN) - NO TEXT","Ghi chú"]
header_fill = PatternFill("solid", fgColor="2F5496"); header_font = Font(bold=True, color="FFFFFF", size=11)
thin = Side(style="thin", color="BFBFBF"); border = Border(left=thin,right=thin,top=thin,bottom=thin)
wrap_top = Alignment(wrap_text=True, vertical="top"); center = Alignment("center","center",wrap_text=True)
ws.append(headers)
for c in range(1,len(headers)+1):
    cc=ws.cell(1,c); cc.fill=header_fill; cc.font=header_font; cc.alignment=center; cc.border=border

prompts_seen=set(); dur_issues=[]
for i,(a,b,fr,vi,scene,video,note) in enumerate(S, start=1):
    start=E[a][0]; end=E[b][1]; dur=round(end-start,1)
    if not (5.0<=dur<=10.1): dur_issues.append((i,dur))
    image=img(scene, "medium shot, eye-level" if i%3 else "medium-wide, soft depth")
    assert image not in prompts_seen, f"DUP image {i}"; prompts_seen.add(image)
    video_full=(f"{ANIM}. Keep the SAME drawn cartoon character unchanged (only her expression and "
                f"movement change), smooth hand-drawn 2D animation. {video} {NOREAL}.")
    tc=f"{hhmmss(start)} - {hhmmss(end)}"
    ws.append([i, tc, dur, fr, vi, image, video_full, note]); r=ws.max_row
    for c in range(1,len(headers)+1):
        cell=ws.cell(r,c); cell.border=border; cell.alignment = center if c in (1,2,3) else wrap_top
    if i%2==0:
        for c in range(1,len(headers)+1): ws.cell(r,c).fill=PatternFill("solid",fgColor="EEF1F8")

for col,w in {"A":6,"B":24,"C":12,"D":42,"E":42,"F":74,"G":60,"H":34}.items():
    ws.column_dimensions[col].width=w
ws.freeze_panes="A2"; ws.row_dimensions[1].height=32
out=r"D:\TLP\KỊCH BẢN\KBP-001_storyboard.xlsx"; wb.save(out)
print("OK scenes:",len(S),"| dur issues:",dur_issues,"| unique prompts:",len(prompts_seen))
