# -*- coding: utf-8 -*-
import sys
try: sys.stdout.reconfigure(encoding="utf-8")
except Exception: pass
import re, openpyxl
from openpyxl.styles import Font, Alignment, PatternFill, Border, Side

SRT = r"D:\TLP\KỊCH BẢN\KBP-002.srt"
def sec(x):
    h,m,r=x.split(":"); s,ms=r.split(","); return int(h)*3600+int(m)*60+int(s)+int(ms)/1000
def hhmmss(v):
    v=round(v); return f"{v//3600:02d}:{(v%3600)//60:02d}:{v%60:02d}"
E={}; n=0
for b in re.split(r"\n\s*\n", open(SRT, encoding="utf-8-sig").read().strip()):
    L=[l for l in b.splitlines() if l.strip()]
    if len(L)<2: continue
    a,bb=L[1].split(" --> "); n+=1; E[n]=(sec(a),sec(bb))

# ---- locked character + style (illustration only, anti-photoreal) ----
CHAR = ("the SAME recurring heroine, identical in every scene: a comic/watercolor-illustrated "
        "woman in her late 30s with a friendly oval face, brown hair pulled back in a low "
        "ponytail with soft side-parted bangs, small teal-green stud earrings, a thin necklace, "
        "a green-and-purple horizontally striped short-sleeve scoop-neck t-shirt, light-blue "
        "high-waisted jeans cuffed at the ankles, and green canvas lace-up sneakers with white "
        "soles, warm calm expression")
STYLE = ("clean comic line-art with soft watercolor coloring, warm natural palette, gentle "
         "cel-style shading, with occasional subtle colorful watercolor paint-splatter accents "
         "(purple, blue, pink, yellow); stylized 2D illustrated characters only — never "
         "photorealistic, no real-person photography; absolutely NO text, letters, words or "
         "numbers anywhere in the frame")
ANIM  = ("2D HAND-DRAWN CARTOON ANIMATION, flat cel-shaded comic illustration with clean ink "
         "outlines and soft watercolor coloring (animated drawing, in the style of an illustrated "
         "storybook / motion-comic)")
NOREAL = ("IMPORTANT STYLE LOCK: everything is a drawn animated cartoon — NOT live action, NOT "
          "photorealistic, NOT 3D CGI, NOT a real human being; the character and all supporting "
          "figures are flat hand-drawn illustrations with visible ink linework and watercolor "
          "shading. No real people, no photographic faces, no text or letters anywhere")
def img(scene, cam):
    return (f"{ANIM}. {scene} The heroine is {CHAR}, kept clearly the central focus, drawn in flat "
            f"cartoon illustration. Supporting figures and props are drawn in the exact same "
            f"hand-drawn cartoon style. {STYLE}. {cam}. {NOREAL}.")

# (firstEntry, lastEntry, FR, VI, image-scene, video, note)
S = [
(1,3,"Votre anniversaire approche, quelqu'un vous demande ce que vous allez faire pour le fêter. Et vous répondez quelque chose qui, sans que vous compreniez pourquoi,",
 "Sinh nhật bạn sắp đến, ai đó hỏi bạn định làm gì để ăn mừng. Và bạn trả lời một điều mà, chẳng hiểu vì sao,",
 "A cozy café table; a simply-drawn friend leans in brightly asking about birthday plans, a small wall calendar with one circled date and a tiny balloon doodle behind them; the heroine pauses, considering her answer with a calm neutral look.",
 "The friend leans in eagerly gesturing; the heroine opens her mouth and gives a small calm shrug as the circled calendar date faintly glows.",
 "Mở đầu: được hỏi về kế hoạch sinh nhật"),
(4,6,"déstabilise tout le monde. « Rien, c'est juste un jour comme un autre. » Et soudain, il se passe une chose curieuse.",
 "khiến mọi người sững người. « Chẳng làm gì, chỉ là một ngày như bao ngày khác. » Và bỗng nhiên, một điều kỳ lạ xảy ra.",
 "Same café: the heroine calmly says it's just an ordinary day; the friend and two nearby simply-drawn people freeze mid-gesture with surprised blinking expressions and a faint puzzled swirl (no text) hovering above them.",
 "The heroine gives a relaxed little shrug; the friend and bystanders freeze mid-motion, eyes widening as a soft puzzled swirl rises.",
 "Câu trả lời khiến mọi người sững sờ"),
(7,9,"Les gens commencent à vous regarder différemment. Vos amis pensent que vous êtes négative. Votre famille croit que vous êtes de mauvaise humeur.",
 "Mọi người bắt đầu nhìn bạn theo cách khác. Bạn bè nghĩ bạn tiêu cực. Gia đình cho rằng bạn đang cáu kỉnh.",
 "Around her: simply-drawn friends whisper with concerned frowns as a small grey rain-cloud forms over her head, while family figures exchange worried looks reading her as moody; she stands centered, calm and a little bemused.",
 "The friends whisper and a small grey cloud forms over her; family figures frown; she stays calm, glancing between them with mild bemusement.",
 "Bị hiểu lầm là tiêu cực / cáu kỉnh"),
(10,11,"Et la société semble convaincue que s'il n'y a pas de gâteau, pas de bougie, pas de photo avec un grand sourire,",
 "Và xã hội dường như tin chắc rằng nếu không có bánh kem, không có nến, không có tấm ảnh với nụ cười rạng rỡ,",
 "Floating around her in flat cartoon style: a birthday cake, a single lit candle, and a framed photo of a big forced smile, each marked with a soft red prohibition-slash; faint society silhouettes point at the missing items while she stands unbothered.",
 "The cake, candle and smiling-photo icons pop up one by one, each crossed by a soft slash, as silhouettes point insistently; she stands calm.",
 "Xã hội: phải có bánh, nến, ảnh cười"),
(12,14,"alors quelque chose ne tourne pas rond chez vous. Mais… Et s'il n'y avait rien qui ne tournait pas rond ?",
 "thì hẳn có gì đó không ổn ở bạn. Nhưng… Nếu chẳng có gì là không ổn cả thì sao?",
 "She stands under a faint heavy spotlight of judgement with small accusing arrow-shapes pointing at her; then the arrows dissolve into soft light as a gentle question-glow blooms above her head, her expression shifting from pressured to thoughtful.",
 "Accusing arrow-shapes press in, then dissolve into soft light; a gentle glow blooms above her head as her face eases from pressured to curious.",
 "Bị cho là 'có gì đó không ổn' – nhưng nếu không?"),
(15,16,"Et si le fait que votre anniversaire vous laisse indifférente révélait quelque chose de vraiment fascinant sur la façon dont votre esprit fonctionne ?",
 "Và nếu việc bạn dửng dưng với sinh nhật của mình lại tiết lộ một điều thật sự thú vị về cách tâm trí bạn vận hành thì sao?",
 "A softly glowing translucent silhouette of a mind made of gentle light hovers beside her, intriguing and warm; she tilts her head studying it with fascination, while a tiny faded birthday cake sits ignored in the corner.",
 "The glowing mind-silhouette pulses and swirls beside her; she tilts her head, eyes lighting with fascination, the little cake forgotten.",
 "Điều này tiết lộ cách tâm trí vận hành"),
(17,19,"Parce que ce comportement, on l'a observé bien plus souvent qu'on ne le croit. Et il cache quelque chose d'inattendu.",
 "Bởi vì hành vi này được quan sát thấy thường xuyên hơn ta tưởng nhiều. Và nó che giấu một điều bất ngờ.",
 "Many small simply-drawn women's portrait-cards arranged like a soft gallery wall around her, more numerous than expected, each calm; one card glows hinting a hidden surprise; she gestures toward them.",
 "The gallery of small portrait-cards softly multiplies around her; one card gently glows as she gestures, hinting at a hidden truth.",
 "Phổ biến hơn ta tưởng – ẩn điều bất ngờ"),
(20,21,"Les femmes que leur anniversaire laisse indifférente ne se ressemblent pas toutes. En réalité,",
 "Những phụ nữ dửng dưng với sinh nhật không hề giống nhau. Trên thực tế,",
 "Three distinctly different simply-drawn women stand apart in a row — clearly different personalities, postures and palettes — while the heroine stands beside them introducing the contrast with an open hand.",
 "The heroine sweeps an open hand across the three different women, who each shift slightly to reveal their distinct demeanor.",
 "Họ không hề giống nhau"),
(22,24,"elles appartiennent souvent à trois profils très différents. Certaines ont appris à ne plus rien attendre. D'autres ont simplement un esprit qui fonctionne autrement.",
 "họ thường thuộc về ba kiểu rất khác nhau. Một số đã học cách không còn mong đợi gì nữa. Số khác đơn giản có một tâm trí vận hành theo cách khác.",
 "She gestures to a soft glowing diagram of three branching paths of light (pure shapes, no text): one path dim and guarded, one busy with floating idea-sparks, one serene; a small woman-silhouette stands at each path's end.",
 "Three glowing paths branch from her gesture and light up in turn — guarded, busy, serene — each with a small silhouette at its end.",
 "Ba kiểu: hết mong đợi / tâm trí khác / nhóm ba"),
(25,28,"Et un petit groupe est arrivé à une conclusion que beaucoup de gens ont du mal à accepter. Commençons par le premier, parce que ce groupe-là n'en parle presque jamais.",
 "Và một nhóm nhỏ đã đi đến một kết luận mà nhiều người khó chấp nhận. Hãy bắt đầu với nhóm đầu tiên, vì nhóm này gần như chẳng bao giờ nói ra.",
 "She steps toward the first of three softly glowing doorways; this door is quiet and slightly dim with a soft finger-to-lips hush silhouette nearby, while the other two doors wait faded behind.",
 "She walks toward the first dim doorway; a soft hush-glow surrounds it as the other two doorways fade gently behind her.",
 "Bắt đầu nhóm 1 – nhóm hiếm khi nói ra"),
(29,31,"Il y a des femmes qui ont cessé de fêter leur anniversaire. Non pas par choix, mais parce qu'elles ont appris à ne plus rien espérer.",
 "Có những phụ nữ đã ngừng tổ chức sinh nhật. Không phải vì lựa chọn, mà vì họ đã học cách không còn hy vọng gì nữa.",
 "A simply-drawn woman quietly closing a box of unused birthday decorations and sliding it onto a high shelf with a resigned gentle expression, faded uninflated balloons inside; the heroine watches with empathy nearby.",
 "The woman gently closes the lid on the unused decorations and pushes the box onto the shelf with a quiet resigned breath; the heroine watches kindly.",
 "Nhóm 1: ngừng vì không còn hy vọng"),
(32,34,"Lorsqu'une personne vit des déceptions répétées, sans jamais pouvoir changer le résultat, l'esprit finit par faire quelque chose de très particulier.",
 "Khi một người trải qua những thất vọng lặp đi lặp lại, mà không bao giờ thay đổi được kết quả, tâm trí cuối cùng làm một điều rất đặc biệt.",
 "Visual metaphor: a simply-drawn figure reaching repeatedly toward a glowing gift that keeps fading away just before her hand, leaving soft motion-trails of repeated attempts; the heroine observes with a thoughtful explanatory gesture.",
 "The figure reaches again and again as the gift fades just out of reach each time, leaving soft repeat-trails; the heroine gestures in gentle explanation.",
 "Thất vọng lặp lại – tâm trí làm điều đặc biệt"),
(35,37,"Il arrête d'essayer. Non pas parce qu'il est blessé, mais parce qu'il tente de se protéger.",
 "Nó ngừng cố gắng. Không phải vì bị tổn thương, mà vì nó đang cố tự bảo vệ mình.",
 "A soft glowing heart-shape gently lowering a translucent protective shield around itself, calm rather than dramatic; the reaching hand from before quietly lowers and rests; muted tender tone.",
 "The reaching hand lowers and rests as a translucent protective shield gently closes around the soft glowing heart.",
 "Ngừng cố gắng để tự bảo vệ"),
(38,38,"Et l'anniversaire peut très facilement devenir une sorte d'épreuve émotionnelle.",
 "Và sinh nhật rất dễ trở thành một kiểu thử thách cảm xúc.",
 "A calendar page with a circled birthday date subtly transforming into a small daunting hurdle/obstacle shape that a tiny figure must face; muted tense tone; the heroine looks on with understanding.",
 "The circled calendar date morphs into a small looming hurdle; the tiny figure hesitates before it as the heroine watches with quiet empathy.",
 "Sinh nhật thành một thử thách cảm xúc"),
(39,42,"Au fond, on attend des choses très précises. On attend que les gens s'en souviennent. On attend de se sentir spécial.",
 "Sâu thẳm bên trong, ta mong đợi những điều rất cụ thể. Ta mong người khác nhớ đến. Ta mong được cảm thấy mình đặc biệt.",
 "Soft thought-bubbles rise around her head showing simple wished-for images: a phone lighting up with remembrance, a warm group turning toward her, a gentle personal spotlight of feeling special; hopeful tender mood.",
 "Gentle thought-bubbles rise around her one by one — a glowing phone, a welcoming group, a soft personal spotlight — with a hopeful wistful look.",
 "Ta âm thầm mong: được nhớ, được đặc biệt"),
(43,44,"On attend que ce jour-là soit différent des autres. Mais quand ces attentes se brisent encore et encore,",
 "Ta mong ngày ấy khác với mọi ngày. Nhưng khi những kỳ vọng đó vỡ vụn hết lần này đến lần khác,",
 "She cradles a delicate glowing 'special day' bubble that develops fine spreading cracks; faint ghost-cracks suggest it has shattered before; her expression tightens with quiet hurt.",
 "The glowing 'special day' bubble in her hands slowly develops spreading cracks; she watches it fracture with a small wince.",
 "Mong ngày khác biệt – nhưng kỳ vọng vỡ vụn"),
(45,47,"l'esprit commence à réajuster ce qu'il espère. Pensez-y un instant. Si vous attendez quelque chose de beau et que cela arrive,",
 "tâm trí bắt đầu điều chỉnh lại những gì nó hy vọng. Hãy ngẫm một chút. Nếu bạn mong một điều đẹp đẽ và điều đó đến,",
 "A glowing balance-scale of light beside her: on one side a hopeful glow rises as a beautiful gift-light actually arrives and lifts it; she watches a soft joyful rise begin; warm tone.",
 "On the glowing scale the hopeful side rises as a beautiful light arrives and lifts it; a soft joyful glow begins to climb.",
 "Tâm trí điều chỉnh hy vọng – nếu điều đẹp đến"),
(48,51,"la joie monte. Mais si vous l'attendez, et que rien ne vient, la chute est encore plus brutale.",
 "niềm vui dâng lên. Nhưng nếu bạn mong chờ, mà chẳng có gì đến, cú rơi còn đau đớn hơn nhiều.",
 "The same balance-scale now: the hopeful glow climbs high then crashes down hard into shadow when nothing arrives, a small figure tumbling with the falling side; muted painful tone.",
 "The hopeful glow climbs then plunges sharply into shadow as nothing arrives; the small figure drops with the falling side.",
 "Mong mà trống không – cú rơi đau hơn"),
(52,54,"Alors, avec le temps, le cœur apprend une chose très simple. Il est plus prudent de ne rien attendre.",
 "Vậy nên, theo thời gian, trái tim học được một điều rất đơn giản. An toàn hơn là đừng mong đợi gì cả.",
 "A soft glowing heart gently settling flat and calm behind a thin protective glass, choosing stillness; faded year-pages drift past behind; resigned-but-peaceful tone; the heroine reflective nearby.",
 "The glowing heart settles flat and still behind soft protective glass as faded year-pages drift by; a calm resigned breath.",
 "Trái tim học: an toàn hơn là đừng mong"),
(55,57,"Et quand une femme dit : « c'est juste un jour comme un autre », ce n'est parfois pas de l'indifférence.",
 "Và khi một người phụ nữ nói: « chỉ là một ngày như bao ngày khác », đôi khi đó không phải là sự dửng dưng.",
 "Close on the heroine saying it calmly, but a faint translucent layer of armor-light shimmers over her chest, revealing the quiet protection beneath the calm surface; soft dual tone.",
 "She calmly says the words; a faint shimmer of armor-light flickers over her chest, hinting at what lies beneath the calm.",
 "Câu nói bình thản – đôi khi không phải dửng dưng"),
(58,62,"C'est une protection, une sorte d'armure émotionnelle, construite tout doucement, année après année. Mais voici ce qui est curieux.",
 "Đó là một sự phòng vệ, một kiểu áo giáp cảm xúc, được dựng lên thật chậm rãi, năm này qua năm khác. Nhưng đây mới là điều kỳ lạ.",
 "She stands wearing a softly glowing translucent suit of gentle 'emotional armor' (delicate light-plates) assembled from many small year-pieces floating into place; dignified, not cold; then her head tilts curiously.",
 "Small year-pieces of light drift in and assemble into gentle translucent armor around her; she then tilts her head curiously.",
 "Áo giáp cảm xúc dựng dần qua năm tháng"),
(63,66,"Toutes celles qui ignorent leur anniversaire ne le font pas à cause de blessures du passé. Il existe un autre groupe, complètement différent.",
 "Không phải tất cả những ai phớt lờ sinh nhật đều làm vậy vì vết thương quá khứ. Có một nhóm khác, hoàn toàn khác biệt.",
 "Split: left, a guarded woman in the faint emotional armor; right, an entirely different bright woman cheerfully absorbed in work with no armor at all; the heroine stands between, gesturing to the clear difference.",
 "The heroine gestures from the guarded armored woman to the bright busy woman; the divide between them softly brightens.",
 "Không phải ai cũng vì vết thương – có nhóm khác"),
(67,68,"Il y a des femmes qui, sincèrement, oublient même la date de leur anniversaire.",
 "Có những phụ nữ thật sự quên luôn cả ngày sinh nhật của mình.",
 "A cheerful absorbed woman at a desk genuinely surprised to notice a wall calendar showing her own birthday has already passed, a light 'oh!' expression, not sad at all; blank sticky-note shapes scattered around (no text).",
 "She glances up from her work, notices the calendar, and gives a light surprised 'oh!' eyebrow-raise — amused and untroubled.",
 "Nhóm 2: thật sự quên cả ngày sinh nhật"),
(69,72,"Pas parce qu'elles sont tristes, pas parce qu'elles évitent quelque chose. Simplement, leur esprit est ailleurs,",
 "Không phải vì họ buồn, không phải vì họ né tránh điều gì. Đơn giản là tâm trí họ đang ở nơi khác,",
 "She sits at home but a soft glowing thought-stream flows out of her head toward floating projects and ideas elsewhere; clearly not sad — engaged and mentally elsewhere; gentle tone.",
 "A glowing thought-stream drifts from her head toward distant floating ideas; she gazes off, absorbed and content, not sad.",
 "Không buồn, không né – tâm trí ở nơi khác"),
(73,76,"occupé par autre chose. C'est fréquent chez les femmes qui vivent très concentrées sur leurs projets, leur travail ou leurs idées.",
 "bận rộn với điều khác. Điều này thường gặp ở những phụ nữ sống rất tập trung vào dự án, công việc hay ý tưởng của mình.",
 "She is deeply focused at a creative workspace surrounded by blueprints, sketches, a glowing laptop, blank sticky shapes and tools (all flat cartoon style, no readable text), fully absorbed and energized.",
 "She works intently across sketches and a glowing laptop, hands moving, eyes bright with focus on her project.",
 "Bận với dự án, công việc, ý tưởng"),
(77,79,"Quand votre esprit est constamment tourné vers la résolution de problèmes, la création, ou la poursuite d'un objectif,",
 "Khi tâm trí bạn liên tục hướng về việc giải quyết vấn đề, sáng tạo, hay theo đuổi một mục tiêu,",
 "Around her concentrating head orbit three soft glowing motifs: interlocking gears (problem-solving), a paintbrush idea-spark (creation), and a small mountain-flag goal-shape (pursuit); intense focus.",
 "The gears turn, the idea-spark flares, the goal-flag plants — the three motifs orbit her focused head in motion.",
 "Giải quyết vấn đề – sáng tạo – theo đuổi mục tiêu"),
(80,82,"les dates commencent à perdre leur importance. Les jours se mélangent, les semaines filent,",
 "ngày tháng bắt đầu mất đi tầm quan trọng. Những ngày hòa lẫn vào nhau, những tuần trôi vụt qua,",
 "A wall calendar whose blank date-cells soften and blur together while pages flutter and fly off like autumn leaves; she walks past barely noticing, mind elsewhere.",
 "Calendar cells blur together and pages flutter off like leaves flying past; she strides by without a glance.",
 "Ngày tháng mờ đi – tuần trôi vụt"),
(83,86,"le calendrier cesse d'être une structure claire, et certains événements finissent rangés quelque part dans un coin de la tête,",
 "lịch không còn là một cấu trúc rõ ràng nữa, và vài sự kiện rốt cuộc bị xếp đâu đó trong một góc tâm trí,",
 "Inside a stylized 'mind room', a neat calendar grid dissolves into loose floating cards drifting toward a dim corner shelf; she absently nudges a few aside while focused elsewhere.",
 "The neat calendar grid loosens into floating cards that drift toward a dim corner shelf; she absently nudges a few aside.",
 "Lịch mất cấu trúc – sự kiện vào góc tâm trí"),
(87,91,"dans la catégorie « pas urgent ». C'est exactement là où vit ce rendez-vous chez le dentiste reporté trois fois, et cette liste de tâches qui ne se termine jamais.",
 "vào ngăn « không khẩn cấp ». Đó chính là nơi nằm cái lịch hẹn nha sĩ bị dời ba lần, và danh sách việc cần làm chẳng bao giờ kết thúc.",
 "A dim 'not urgent' corner shelf holding faded cards: a tooth/dentist symbol stamped with three little reschedule-arrows, and a long curling to-do scroll with endless empty checkboxes (no text); she gestures to it wryly.",
 "She gestures to the dim shelf where the dentist-tooth card flips through three reschedule-arrows and the to-do scroll keeps unrolling endlessly.",
 "Ngăn 'không khẩn cấp': hẹn nha sĩ, to-do bất tận"),
(92,93,"Ce n'est pas un manque d'amour-propre. C'est simplement un esprit occupé par trop de choses à la fois.",
 "Đó không phải là thiếu lòng tự trọng. Đó đơn giản là một tâm trí bận rộn với quá nhiều thứ cùng lúc.",
 "Her head depicted with many soft glowing thought-threads all active at once — tangled yet bright and capable, not negative; a clear warm confident expression underneath: busy, not broken.",
 "Many glowing thought-threads buzz around her head at once; she smiles confidently underneath, clearly capable, not lacking.",
 "Không phải thiếu tự trọng – chỉ là quá bận"),
(94,97,"Mais il y a un troisième groupe, et c'est sans doute le plus intéressant. Ces femmes-là n'oublient pas leur anniversaire. Elles ne l'évitent pas par douleur non plus.",
 "Nhưng có một nhóm thứ ba, và có lẽ là nhóm thú vị nhất. Những phụ nữ này không quên sinh nhật. Họ cũng không né tránh nó vì đau khổ.",
 "She steps toward the third glowing doorway, the brightest and warmest of the three; beyond it a serene self-assured woman stands calmly with no armor and no distraction — simply whole.",
 "She approaches the bright third doorway; beyond it a serene self-assured woman stands calmly, glowing softly, fully at ease.",
 "Nhóm 3 (thú vị nhất): không quên, không né vì đau"),
(98,103,"Simplement, elles n'en ont pas besoin. Elles ont observé tout le rituel : les bougies, les félicitations, la fête,",
 "Đơn giản là họ không cần đến nó. Họ đã quan sát toàn bộ nghi thức: những ngọn nến, những lời chúc, bữa tiệc,",
 "This serene woman stands a little apart at a lively party, calmly observing the whole ritual — a cake with candles, friends offering congratulations, festive bustle — with a gentle knowing smile, not drawn in.",
 "At the lively party she watches the candles glow and friends celebrate, smiling gently and knowingly, content to simply observe.",
 "Họ đã quan sát hết nghi thức: nến, lời chúc, tiệc"),
(104,106,"et elles sont arrivées à une conclusion très simple : elles n'ont pas besoin de tout cela pour se sentir bien.",
 "và họ đi đến một kết luận rất đơn giản: họ không cần tất cả những thứ đó để cảm thấy ổn.",
 "She steps back from the party into a softly lit calm space, perfectly content on her own; the festive scene glows warmly but small behind her; a settled peaceful smile.",
 "She steps back from the festive glow into calm warm light, breathing easy with a settled peaceful smile, content alone.",
 "Kết luận: không cần thứ đó để thấy ổn"),
(107,110,"Parce qu'au fond, les femmes les plus en paix avec elles-mêmes ne dépendent pas autant des événements extérieurs pour se sentir bien.",
 "Bởi vì sâu thẳm bên trong, những phụ nữ bình an nhất với chính mình không phụ thuộc nhiều vào những sự kiện bên ngoài để thấy ổn.",
 "A serene portrait: she sits with a steady warm inner glow at her core that needs no outside spark, while faint external event-icons (a party, fireworks) drift by without affecting her steady light.",
 "Her steady inner glow holds firm as faint party and firework icons drift past without changing it; calm and self-contained.",
 "Bình an nội tâm – không lệ thuộc sự kiện ngoài"),
(111,114,"Leur sentiment de valeur vient de l'intérieur, pas d'une date précise, pas d'une célébration, et certainement pas du fait que trente personnes",
 "Cảm giác về giá trị của họ đến từ bên trong, không phải từ một ngày cụ thể, không phải từ một buổi tiệc, và chắc chắn không phải từ việc ba mươi người",
 "Her chest glows with a self-sourced light while around her faded crossed-out symbols of a calendar date and a celebration drift away unneeded; she stands grounded and self-possessed.",
 "Her chest-glow brightens from within while the faded date and celebration symbols drift away crossed-out; she stands grounded and sure.",
 "Giá trị đến từ bên trong, không từ ngày/tiệc"),
(115,116,"leur chantent une chanson un peu gênante dans un restaurant. Ces femmes ont compris quelque chose de précieux.",
 "hát cho họ một bài hát hơi ngượng ngùng trong nhà hàng. Những phụ nữ này đã hiểu ra một điều quý giá.",
 "A restaurant scene: simply-drawn waiters and diners cluster around an empty chair singing awkwardly toward where she'd be, a small candle-dessert in hand, while she watches from a calm distance with a kind amused smile, unbothered.",
 "The restaurant group claps and sings awkwardly toward the empty seat; she watches from afar with a warm amused smile, at peace.",
 "Bài hát ngượng ở nhà hàng – họ hiểu điều quý giá"),
(117,119,"Que l'on passe souvent sa vie à courir après le prochain moment spécial, la prochaine réussite, la prochaine célébration,",
 "Rằng ta thường dành cả đời để chạy theo khoảnh khắc đặc biệt tiếp theo, thành công tiếp theo, lễ kỷ niệm tiếp theo,",
 "She watches a simply-drawn figure running along a path chasing a series of receding glowing rewards always just ahead: a 'special moment' star, a trophy, a party-popper; a little out of breath.",
 "The figure runs chasing the receding glowing star, trophy and party-popper that always stay just ahead; she observes thoughtfully.",
 "Cả đời chạy theo khoảnh khắc/thành công tiếp theo"),
(120,124,"le prochain pic de bonheur. Mais ces pics ne durent presque jamais. Alors certaines femmes, tout simplement, descendent de cette roue.",
 "đỉnh cao hạnh phúc tiếp theo. Nhưng những đỉnh cao đó gần như chẳng bao giờ kéo dài. Vậy nên một số phụ nữ, đơn giản là, bước xuống khỏi cái vòng quay đó.",
 "A glowing wheel of happiness-peaks (little spikes that flare bright then instantly fade) with the running figure inside; then the heroine calmly steps off the wheel onto solid calm ground.",
 "Happiness-peaks flare and vanish on the spinning wheel; the heroine calmly steps off it onto steady ground, exhaling with relief.",
 "Đỉnh hạnh phúc chóng tàn – bước xuống vòng quay"),
(125,128,"Elles n'attendent plus un jour spécial dans l'année pour se sentir importante. Elles ont appris à se sentir entière un mardi tout à fait ordinaire,",
 "Họ không còn chờ một ngày đặc biệt trong năm để thấy mình quan trọng. Họ đã học cách thấy mình trọn vẹn vào một ngày thứ Ba hết sức bình thường,",
 "An ordinary weekday kitchen morning in soft daylight: she stands relaxed feeling quietly whole and content on a plain Tuesday — a mug, a simple breakfast — radiating gentle self-contained warmth.",
 "In plain morning light she sips from her mug and looks around her ordinary kitchen with a quietly whole, contented smile.",
 "Thấy trọn vẹn vào một thứ Ba bình thường"),
(129,131,"et curieusement, cela peut déranger les autres. Parce que cela brise une croyance très répandue,",
 "và lạ thay, điều đó lại khiến người khác khó chịu. Bởi nó phá vỡ một niềm tin rất phổ biến,",
 "She stands serene while a few simply-drawn onlookers frown, unsettled by her calm self-sufficiency; a faint shared 'belief' bubble hovering between the onlookers visibly cracks.",
 "The onlookers frown, unsettled, as a shared belief-bubble above them develops a crack; she remains serene and unbothered.",
 "Sự an nhiên ấy lại làm người khác khó chịu"),
(132,135,"l'idée que tout le monde devrait vouloir les mêmes choses, que tout le monde a besoin d'attention, que tout le monde veut faire la fête. Mais ce n'est pas vrai.",
 "ý niệm rằng ai cũng nên muốn những điều giống nhau, rằng ai cũng cần sự chú ý, rằng ai cũng muốn tiệc tùng. Nhưng điều đó không đúng.",
 "A row of identical simply-drawn party-hat figures all facing one way in lockstep, while the heroine stands apart facing a different, calmer direction — clearly her own person; gentle but firm contrast.",
 "The row of identical party-hat figures sways in unison; the heroine turns calmly the other way, distinct and at ease.",
 "Niềm tin 'ai cũng giống nhau' – nhưng không đúng"),
(136,139,"Certaines femmes ont simplement déjà résolu cette question, à l'intérieur. Pourtant, toutes celles qui évitent leur anniversaire",
 "Một số phụ nữ đơn giản đã giải quyết xong câu hỏi đó, từ bên trong. Tuy nhiên, không phải tất cả những ai né tránh sinh nhật",
 "She presses a hand to her chest where a softly resolved settled glow rests (the question answered within); then her expression turns gently cautionary as she gestures toward a different, more shadowed group nearby.",
 "A settled glow rests at her chest; she then turns with a gentle cautioning gesture toward a dimmer group nearby.",
 "Đã giải quyết từ bên trong – nhưng không phải ai cũng vậy"),
(140,142,"ne le font pas depuis un endroit sain. Pour certaines, la raison est très différente. Imaginez ceci.",
 "đều làm vậy từ một nơi lành mạnh. Với một số người, lý do rất khác. Hãy hình dung điều này.",
 "A soft doorway of memory opening into a warmer-tinted nostalgic haze; she gestures the viewer toward it invitingly as the present room dims into a gentle glow.",
 "A memory-doorway softly opens into a warm hazy glow; she gestures the viewer toward it as the present dims into nostalgia.",
 "Có người vì lý do khác – hãy hình dung"),
(143,146,"Vous avez huit ans, c'est votre anniversaire. Vous attendez ce jour depuis des semaines. Vous l'avez raconté à tout le monde.",
 "Bạn lên tám tuổi, hôm nay là sinh nhật bạn. Bạn đã chờ ngày này suốt nhiều tuần. Bạn đã kể cho tất cả mọi người nghe.",
 "Flashback in warm storybook tones: a simply-drawn excited 8-year-old girl in a party hat, beaming, clearly having told everyone — eager little friends and a chalk countdown implied; pure childlike anticipation.",
 "The little girl bounces with excitement in her party hat, beaming and gesturing as she eagerly tells everyone about her big day.",
 "Hồi tưởng: cô bé 8 tuổi háo hức chờ sinh nhật"),
(147,151,"Dans votre tête, vous aviez imaginé des ballons, des cadeaux, des gens réunis. Et quand le jour arrive,",
 "Trong đầu, bạn đã tưởng tượng ra bóng bay, quà cáp, mọi người tụ họp. Và khi ngày ấy đến,",
 "The child's big imagination-bubble overflows with balloons, wrapped gifts and a happy crowd; below it the real, modest room is smaller and quieter; she stands at the doorway as the day begins.",
 "Her imagination-bubble brims with balloons, gifts and crowds; then she steps into the real, quieter room and pauses.",
 "Tưởng tượng bóng bay, quà, mọi người – rồi ngày đến"),
(152,153,"tout semble beaucoup plus petit que ce que vous aviez espéré. Peut-être qu'une personne importante n'est pas venue.",
 "mọi thứ dường như nhỏ bé hơn nhiều so với điều bạn đã hy vọng. Có thể một người quan trọng đã không đến.",
 "The modest little party: a small cake, a few balloons, a couple of guests — visibly smaller than the imagined version lingering faintly above; the child's smile flickers as she notices one empty chair for an absent important person.",
 "The child looks around the modest party, her smile faltering as her eyes land on the empty chair of someone who didn't come.",
 "Thực tế nhỏ bé hơn – một người quan trọng vắng mặt"),
(154,155,"Peut-être que quelqu'un a oublié de vous souhaiter. Peut-être que personne ne semblait aussi enthousiaste que vous,",
 "Có thể ai đó đã quên chúc mừng bạn. Có thể chẳng ai có vẻ hào hứng như bạn,",
 "The child holds a small unlit sparkler while nearby simply-drawn adults are distracted and a phone shows a forgotten reminder; no one matches her excitement; her shoulders lower slightly.",
 "The child waits hopefully as the distracted adults look away; her bright expression dims and her shoulders gently lower.",
 "Có người quên chúc – chẳng ai hào hứng như em"),
(156,158,"et quelque chose se déplace à l'intérieur. Vous ne faites pas de scène. Vous ne dites rien.",
 "và một điều gì đó dịch chuyển bên trong bạn. Bạn không làm ầm lên. Bạn chẳng nói gì.",
 "Close on the child's face quietly absorbing the letdown — a tiny internal shift shown as a small dimming glow in her chest; she stays composed, lips pressed, making no fuss at all.",
 "The child's chest-glow dims a touch; she presses her lips and stays quiet, composing herself without a word.",
 "Có gì đó dịch chuyển bên trong – em im lặng"),
(159,161,"Mais vous commencez à baisser vos attentes. L'année suivante, vous espérez un peu moins.",
 "Nhưng bạn bắt đầu hạ thấp kỳ vọng của mình. Năm sau, bạn hy vọng ít hơn một chút.",
 "A small glowing dial of 'hope' that the child gently turns down a notch, beside a faint 'next year' calendar page softly turning; muted tender tone.",
 "The child quietly turns the glowing hope-dial down one notch as a faint next-year page turns beside her.",
 "Bắt đầu hạ kỳ vọng – năm sau mong ít hơn"),
(162,166,"Et celle d'après, encore un peu moins. Et voici ce qui est troublant. Notre cœur ne se souvient pas seulement de certaines dates.",
 "Và năm sau nữa, lại ít hơn một chút. Và đây là điều đáng suy ngẫm. Trái tim ta không chỉ ghi nhớ vài ngày tháng.",
 "A row of birthday candles, each year's candle burning a little lower than the last; then a transition back to the adult heroine touching her chest where a soft glowing heart holds not just dates but feelings.",
 "Each year's candle burns lower than the last; the scene returns to the adult heroine resting a hand on her chest, the heart-glow pulsing.",
 "Mỗi năm mong ít hơn – trái tim nhớ cả cảm xúc"),
(167,169,"Il retient aussi les émotions qui leur sont attachées, même des années plus tard. Cette petite fille de huit ans,",
 "Nó còn lưu giữ cả những cảm xúc gắn liền với chúng, kể cả nhiều năm sau. Cô bé tám tuổi ấy,",
 "A gentle double-exposure: the adult heroine with, softly overlaid within her, the 8-year-old girl still present; warm-sad tone; a faint thread of light links the past feeling to the present heart.",
 "The 8-year-old image gently surfaces overlaid within the adult heroine, linked by a soft thread of light; a tender wistful look.",
 "Tim giữ cả cảm xúc – cô bé 8 tuổi ấy"),
(170,172,"elle est toujours là, à l'intérieur. Il y a aussi quelque chose d'autre.",
 "vẫn còn ở đó, bên trong bạn. Còn có một điều khác nữa.",
 "The heroine gently places a comforting hand over her own heart where the small girl's glow rests, a tender protective gesture; then her eyes lift, signalling another point is coming.",
 "She rests a comforting hand over her heart where the little glow sits, then lifts her gaze thoughtfully toward a new thought.",
 "Cô bé vẫn ở đó – còn một điều khác nữa"),
(173,175,"Certaines femmes évitent, sans le savoir, les situations qui pourraient confirmer leur peur sur elles-mêmes.",
 "Một số phụ nữ né tránh, mà không hề hay biết, những tình huống có thể xác nhận nỗi sợ của họ về chính mình.",
 "She instinctively steps around a softly glowing doorway marked by a faint anxious knot-of-light (a fear), her path curving away without her realizing; a subtle unaware expression.",
 "Her path subtly curves around the faintly glowing fear-doorway; she avoids it without noticing, her eyes elsewhere.",
 "Né tránh vô thức tình huống xác nhận nỗi sợ"),
(176,178,"Autrement dit, certaines cessent de fêter leur anniversaire. Non pas parce qu'elles n'en ont pas besoin,",
 "Nói cách khác, một số ngừng tổ chức sinh nhật. Không phải vì họ không cần đến nó,",
 "A woman gently waving away a birthday-celebration setup, pushing the idea softly aside; but a faint wistful longing-glow lingers in her eyes hinting she may actually want it; the heroine observes knowingly.",
 "The woman softly waves away the birthday setup, yet a faint longing-glow flickers in her eyes; the heroine watches knowingly.",
 "Ngừng tổ chức – không phải vì không cần"),
(179,182,"mais parce qu'elles craignent que si elles le fêtent et que ce n'est pas parfait, cela vienne confirmer quelque chose de douloureux. Alors elles préfèrent ne pas essayer.",
 "mà vì họ sợ rằng nếu họ tổ chức và nó không hoàn hảo, điều đó sẽ xác nhận một điều gì đó đau đớn. Vậy nên họ thà không thử còn hơn.",
 "A fragile glowing 'perfect party' bubble she dares not touch for fear it cracks, a faint painful shadow waiting behind it to be confirmed; she withdraws her hand and turns away protectively.",
 "She reaches toward the fragile perfect-party bubble, hesitates as a crack threatens, then withdraws her hand and turns away.",
 "Sợ không hoàn hảo sẽ xác nhận điều đau – thà không thử"),
(183,184,"C'est une forme d'auto-protection. Et la différence entre ces deux choses est essentielle.",
 "Đó là một dạng tự bảo vệ. Và sự khác biệt giữa hai điều này là cốt yếu.",
 "She holds a small protective shield of soft light (self-protection) while, beside her, two clearly different glowing symbols — one open and free, one shielded and fearful — that she weighs with a serious thoughtful look.",
 "She holds the soft shield, then looks between the free symbol and the fearful one, weighing the essential difference seriously.",
 "Tự bảo vệ – và sự khác biệt cốt yếu giữa hai điều"),
(185,188,"Parce qu'il y a un monde entier entre ne pas avoir besoin de la fête et la désirer sans s'autoriser à la vouloir.",
 "Bởi có cả một khoảng cách mênh mông giữa việc không cần bữa tiệc và việc khao khát nó mà không cho phép mình được mong muốn.",
 "A wide glowing gap between two islands of light: one a serene 'no-need' calm-glow, the other a yearning 'silenced wish' that reaches across but holds itself back; she stands contemplating the chasm between them.",
 "She gazes across the glowing chasm between the serene island and the yearning one, whose reaching light pulls back; a contemplative look.",
 "Khác biệt giữa 'không cần' và 'khao khát mà kìm nén'"),
(189,193,"Si vous êtes une femme que son anniversaire laisse indifférente, posez-vous une question, en toute honnêteté :",
 "Nếu bạn là người phụ nữ dửng dưng với sinh nhật của mình, hãy tự hỏi một câu, thật lòng:",
 "She turns directly to the viewer with a sincere, gentle but searching expression, one hand open in honest invitation, a soft mirror beside her reflecting a thoughtful self-questioning; intimate light.",
 "She turns to the viewer with a sincere searching look, opening one hand in honest invitation as the soft mirror beside her gleams.",
 "Hãy thật lòng tự hỏi một câu"),
(194,197,"est-ce de la liberté ou de la peur ? Vous seule connaissez la réponse. Mais le simple fait que vous y réfléchissiez",
 "đó là sự tự do hay là nỗi sợ? Chỉ mình bạn biết câu trả lời. Nhưng chỉ riêng việc bạn ngẫm nghĩ về nó",
 "Two softly glowing paths before her at a fork: one bright and open ('freedom'), one shadowed ('fear'); she stands reflecting honestly with a hand to her chin — only she can choose.",
 "She stands at the glowing fork between the bright freedom-path and the shadowed fear-path, reflecting quietly with a hand to her chin.",
 "Tự do hay nỗi sợ? – chỉ bạn biết"),
(198,199,"en dit déjà beaucoup. Parce que peut-être que depuis des années,",
 "đã nói lên rất nhiều rồi. Bởi có lẽ suốt nhiều năm qua,",
 "A gentle glow kindles above her head simply from the act of reflecting, while behind her a long faded calendar-trail of past years stretches into the distance; a thoughtful dawning tone.",
 "A soft glow kindles above her head as she reflects; behind her a long trail of faded past-year pages stretches into the distance.",
 "Việc bạn nghĩ đã nói lên nhiều – suốt nhiều năm qua"),
(200,203,"nous mesurons mal ce que signifie s'aimer soi-même. On nous a appris que célébrer, c'est se donner de l'importance,",
 "chúng ta đã hiểu sai ý nghĩa của việc yêu thương chính mình. Người ta dạy ta rằng ăn mừng là tự cho mình tầm quan trọng,",
 "A faded old lesson-scene: simply-drawn figures equating a loud party with self-worth (a party-popper raised on a pedestal); she studies it with a questioning, re-examining expression.",
 "She studies the old scene of a party-popper raised on a pedestal as 'self-worth', her expression questioning the equation.",
 "Ta hiểu sai về yêu bản thân – bị dạy 'ăn mừng = quan trọng'"),
(204,207,"que faire une fête, c'est prouver qu'on tient à sa vie. Mais peut-être que le véritable amour de soi ne ressemble pas toujours à une fête.",
 "rằng mở tiệc là chứng tỏ ta trân trọng cuộc đời mình. Nhưng có lẽ tình yêu bản thân đích thực không phải lúc nào cũng giống một bữa tiệc.",
 "She gently sets aside the loud party-popper symbol and instead cups a small warm steady self-love glow in her hands; the noisy festive imagery fades behind into soft calm.",
 "She lowers the party-popper symbol and cups a small warm self-love glow in her hands as the festive noise fades into calm.",
 "Yêu bản thân thật sự không phải lúc nào cũng là tiệc"),
(208,211,"Peut-être qu'il ressemble parfois à quelque chose de bien plus silencieux : accepter qu'un jour de plus sur le calendrier soit déjà suffisant. Peut-être qu'une femme qui regarde cette vidéo",
 "Có lẽ đôi khi nó giống một điều gì đó lặng lẽ hơn nhiều: chấp nhận rằng thêm một ngày trên cuốn lịch đã là đủ. Có lẽ một người phụ nữ đang xem video này",
 "A serene quiet image: she sits peacefully holding a single calm calendar-day glowing softly as 'enough'; then she gestures gently toward the viewer, acknowledging the woman watching; tranquil tone.",
 "She holds a single softly glowing calendar-day with quiet acceptance, then turns to gesture warmly toward the viewer.",
 "Có lẽ nó lặng lẽ hơn: thêm một ngày đã là đủ"),
(212,214,"et s'est pourtant sentie parfaitement en paix. Si c'est votre cas, vous n'êtes pas cassée.",
 "và vậy mà vẫn cảm thấy hoàn toàn bình yên. Nếu đó là trường hợp của bạn, bạn không hề hỏng hóc.",
 "A tender scene of a woman spending her birthday peacefully alone — a small single cupcake, a book, soft window light — genuinely serene; then the heroine turns to reassure the viewer warmly.",
 "The woman alone smiles peacefully over her single cupcake in soft light; the heroine turns to the viewer with a warm reassuring nod.",
 "Một mình mà vẫn bình yên – bạn không hỏng hóc"),
(215,217,"Vous appartenez simplement à ce groupe de femmes qui n'ont besoin de la permission de personne pour se sentir entières.",
 "Bạn chỉ đơn giản thuộc về nhóm phụ nữ không cần sự cho phép của bất kỳ ai để cảm thấy mình trọn vẹn.",
 "She stands tall and self-assured, gently glowing, as faint 'permission' tokens offered by others drift toward her and dissolve away unneeded; complete and whole on her own; quietly empowered.",
 "Faint permission-tokens drift toward her and dissolve unneeded; she stands taller, a soft whole glow rising, quietly empowered.",
 "Không cần ai cho phép để thấy mình trọn vẹn"),
(218,219,"Et si cette vidéo est apparue sur votre écran aujourd'hui, ce n'est peut-être pas un hasard.",
 "Và nếu video này xuất hiện trên màn hình của bạn hôm nay, có lẽ đó không phải là tình cờ.",
 "A soft glowing screen-light reaches outward toward the viewer like a gentle ray of fate; she sits calmly gesturing toward it with a knowing, meaningful smile; warm intimate setting.",
 "A gentle ray of screen-light reaches outward; she gestures toward it with a knowing meaningful smile, as if it were meant to be.",
 "Video xuất hiện hôm nay – có lẽ không tình cờ"),
(220,222,"Si vous avez déjà passé un anniversaire sans le fêter, et que vous vous êtes sentie parfaitement bien,",
 "Nếu bạn từng trải qua một sinh nhật mà không tổ chức, và bạn cảm thấy hoàn toàn ổn,",
 "She reflects warmly, recalling a calm uncelebrated birthday that felt good — a peaceful ordinary scene glowing softly inside a thought-bubble; an inviting, validating expression toward the viewer.",
 "A soft thought-bubble shows a calm uncelebrated birthday; she smiles warmly and turns an inviting, validating look to the viewer.",
 "Nếu bạn từng có sinh nhật không tổ chức mà vẫn ổn"),
(223,225,"laissez un commentaire tranquille en bas. Et si ce sujet sur l'esprit humain vous touche, abonnez-vous.",
 "hãy để lại một bình luận nhẹ nhàng bên dưới. Và nếu chủ đề về tâm trí con người này chạm đến bạn, hãy đăng ký kênh.",
 "She gestures warmly downward toward an implied comment area, then toward a soft glowing heart/subscribe-shape (no text or letters), inviting and friendly; cozy backdrop with subtle paint-splatter accents.",
 "She gestures invitingly downward, then toward a soft glowing heart-shape, with an encouraging friendly nod.",
 "Mời để lại bình luận và đăng ký kênh"),
(226,228,"Parce que la prochaine vidéo pourrait expliquer quelque chose sur vous que vous n'avez pas encore découvert.",
 "Bởi video tiếp theo có thể giải thích một điều về bạn mà bạn còn chưa khám phá ra.",
 "She gestures forward toward a soft glowing doorway of light hinting at the next video and an undiscovered insight; an anticipatory, warm forward-looking expression with a gentle farewell warmth.",
 "She gestures toward the glowing doorway of light with an anticipatory smile, hinting at an undiscovered insight, then a soft farewell nod.",
 "Video sau có thể hé lộ điều bạn chưa khám phá"),
]

wb=openpyxl.Workbook(); ws=wb.active; ws.title="Storyboard KBP-002"
headers=["STT","Timecode (bắt đầu - kết thúc)","Thời lượng (giây)","Nội dung gốc (FR)",
         "Bản dịch tiếng Việt","Image Prompt (EN) - NO TEXT","Video Prompt (EN) - NO TEXT","Ghi chú"]
hf=PatternFill("solid",fgColor="2F5496"); hfont=Font(bold=True,color="FFFFFF",size=11)
thin=Side(style="thin",color="BFBFBF"); bd=Border(left=thin,right=thin,top=thin,bottom=thin)
wrap=Alignment(wrap_text=True,vertical="top"); ctr=Alignment("center","center",wrap_text=True)
ws.append(headers)
for c in range(1,len(headers)+1):
    cc=ws.cell(1,c); cc.fill=hf; cc.font=hfont; cc.alignment=ctr; cc.border=bd
seen=set(); vseen=set(); issues=[]
for i,(a,b,fr,vi,scene,video,note) in enumerate(S,1):
    start=E[a][0]; end=E[b][1]; dur=round(end-start,1)
    if not (5.0<=dur<=10.05): issues.append((i,dur))
    image=img(scene,"medium shot, eye-level" if i%3 else "medium-wide, soft depth")
    video_full=(f"{ANIM}. Keep the SAME drawn cartoon character unchanged (only her expression and "
                f"movement change), smooth hand-drawn 2D animation. {video} {NOREAL}.")
    assert image not in seen and video_full not in vseen, f"DUP {i}"
    seen.add(image); vseen.add(video_full)
    ws.append([i, f"{hhmmss(start)} - {hhmmss(end)}", dur, fr, vi, image, video_full, note]); r=ws.max_row
    for c in range(1,len(headers)+1):
        cell=ws.cell(r,c); cell.border=bd; cell.alignment=ctr if c in (1,2,3) else wrap
    if i%2==0:
        for c in range(1,len(headers)+1): ws.cell(r,c).fill=PatternFill("solid",fgColor="EEF1F8")
for col,w in {"A":6,"B":24,"C":12,"D":44,"E":44,"F":76,"G":62,"H":34}.items():
    ws.column_dimensions[col].width=w
ws.freeze_panes="A2"; ws.row_dimensions[1].height=32
out=r"D:\TLP\KỊCH BẢN\KBP-002_storyboard.xlsx"; wb.save(out)
print("OK scenes:",len(S),"| dur issues:",issues,"| uniq img:",len(seen),"| uniq vid:",len(vseen),
      "| span", round(E[S[0][0]][0],1),"->",round(E[S[-1][1]][1],1))
